[package]
name = "redfish_util"
version = "0.0.5"
authors = ["Rob Johnston <rob.johnston@joyent.com>"]
license = "MIT"

[dependencies]
getopts = "0.2"
lazy_static = "1.3.0"
reqwest = "0.9.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
